name: Test populated topbar

on: [push]

jobs:
  run-populated-topbar-e2e-test:
    runs-on: ubuntu-latest
    name: A job to test dummy test
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: hadi-ansari161/populated-topbar-actions@v19
        with:
          application_url: 'https://stage.mysystems.axis.com/'
          username: ${{ secrets.E2E_USER }}
          password: ${{ secrets.E2E_PASSWORD }}
          # application_url: 'https://playwright.dev/'
