name: Main workflow

on: [push]

jobs:
  main-job-1:
    runs-on: ubuntu-latest
    name: test job 1
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: access secrets
        id: echo-secret
        env:
          TEST: ${{ secrets.DUMMY_SECRET }}
        if: env.TEST == 'Dummy'
        run: echo could read the secret
      