name: Main workflow

on: [push]

jobs:
  main-job-1:
    runs-on: ubuntu-latest
    name: test job 1
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: access secrets
        id: echo-secret
        run: echo secret is => ${{ secrets.DUMMY_SECRET }}
      