name: Main workflow

on: [push]

jobs:
  main-job-1:
    runs-on: ubuntu-latest
    name: test job 1
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: access secrets
        id: echo-secret
        env:
          TEST: ${{ secrets.DUMMY_SECRET }}
        if: env.TEST == 'Dummy'
        run: echo could read the secret
      - uses: actions/upload-artifact@v4
        id: greeting-file
        with:
          name: greeting-file-name
          path: greeting.txt
          retention-days: 1

  download-artifact:
    runs-on: ubuntu-latest
    needs: [main-job-1]
    steps:
      - uses: actions/download-artifact@v4
        id: download-artifact
        with:
          name: greeting-file-name
          path: .
      - name: print the greeting content
        run: |
          ls
          cat greeting.txt